name: Action docs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update workflow docs
        uses: tj-actions/auto-doc@v2
        with:
          filename: .github/workflows/workflow.yml
          reusable: true
      - name: Update readme in the repository
        if: github.event_name != 'pull_request'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(ci): Updating readme"
