name: Ultra Reusable Workflow

on:
  workflow_call:
    inputs:
      aws_region:
        description: The full name of the region
        required: true
        type: string
    secrets:
      aws_secret_access_key:
        description: AWS Secret Access Key
        required: true

jobs:
  aws:
    name: My AWS
    runs-on: ubuntu-latest
    steps:
      - name: Hi
        run: echo "hi"
